apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-customer-objects-gateway
spec:
  image: "ghcr.io/fintlabs/fint-customer-objects-gateway:sha-0000000"
  database:
    database: flais
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'flais-io.fint-customer-objects.*'
  onePassword:
    itemPath: dummy
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m

