apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
  - onepassword.yaml
  - namespace.yaml
commonLabels:
  app.kubernetes.io/name: pgerator
  app.kubernetes.io/instance: flais-pgerator
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/managed-by: GA
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: fintlabs-application-infrastructure-services
  fintlabs.no/team: flais
  fintlabs.no/org-id: flais.io